server:
  port: 6010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        -
          id: reservation-service
          predicates:
            - Path=/reservations/**
          uri: "http://localhost:6012/"
        -
          id: user-service
          predicates:
            - Path=/users/**
          uri: "http://localhost:6011/"
    kubernetes:
      discovery:
        all-namespaces: true
#      config:
#        enabled: true