---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: damithme/travel-lodge-user-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 6011
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
  labels:
    app: reservation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      containers:
        - name: reservation-service
          image: damithme/travel-lodge-reservation-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 6011
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - name: http
      port: 8080
      targetPort: 6011

---
apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  labels:
    app: reservation-service
spec:
  type: NodePort
  selector:
    app: reservation-service
  ports:
    - name: http
      port: 8080
      targetPort: 6012