
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/damithme/travel-lodge-config-repo.git
          clone-on-start: true
          search-paths:
            - user-service
            - reservation-service
            - extra-service
            - payment-service
server:
  port: 8888