version: '3.7'
services:
  mongodb_container:
    user: $UID
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: auth
      MONGO_USERNAME: admin
      MONGO_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/mongodb
      - .mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro